# Nombre del workflow que aparecerá en GitHub Actions.
name: Build and Push Docker Image

# Evento que activa el workflow: cada vez que haya un push a la rama "main".
on:
  push:
    branches: [ "main" ]

jobs:
  # Nombre del job que se ejecutará.
  build-and-push:
    # Tipo de máquina virtual donde se ejecutará el trabajo.
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Obtener el código del repositorio dentro del runner.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 2: Iniciar sesión en Docker Hub usando los secretos configurados en GitHub.
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # Nombre de usuario almacenado como secreto
          password: ${{ secrets.DOCKER_PASSWORD }}   # Token de acceso almacenado como secreto

      # Paso 3: Construir y subir la imagen Docker a tu repositorio en Docker Hub.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true                                   # Activar el envío a Docker Hub
          tags: u6951357081/miapp:latest               # Etiqueta de la imagen en Docker Hub

